services:
  ranger-build:
    container_name: ranger-build
    build:
      context: .
      dockerfile: ./ranger-build/Dockerfile
      args:
        BUILD_USER: ${BUILD_USER}
    environment:
      MAVEN_OPTS: -Dmaven.repo.local=/home/build/.m2
      MAVEN_CONFIG: /home/build/.m2
      HOME: /home/build
      BUILD_USER: ${BUILD_USER}
      PARALLEL: ${PARALLEL}
    user: ${BUILD_USER}
    # userns_mode: keep-id:uid=${BUILD_USER}
    working_dir: /home/build
    env_file:
      - .env
    volumes:
      - ./build-src:/build-src:rw,z,U
      - ${M2_CACHE}:/home/build/.m2:rw,z,U
      - ./ranger-build/clone-n-build.sh:/usr/local/bin/clone-n-build.sh:rw,z,U
    command:
      - bash
      - -c
      - |
        clone-n-build.sh
