name: Relase Build
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hienduyph/ranger
  VERSION: 3.0.0

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: apache/ranger
          ref: 'master'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.x
          cache: npm
          cache-dependency-path: security-admin/src/main/webapp/package-lock.json

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: sudo apt update && apt install gcc curl -y
        name: install core packages


      - run: git checkout "${{ github.ref_name }}"
        name: checkout commit ${{ github.ref_name }}

      - name: update version
        run: |
          mvn versions:set -DnewVersion=${{env .VERSION }}-${{ github.ref_name }}

      - run: mvn -DskipTests package
        name: build

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Ranger Admin Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ranger-admin/Dockerfile
          push: true
          tags: admin-${{env.VERSION}}-${{github.ref_name}}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REVISION=${{github.ref_name}}
            VERSION=${{env.VERSION}}
          

      - name: Ranger UserSync Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ranger-usersync/Dockerfile
          push: true
          tags: usersync-${{env.VERSION}}-${{github.ref_name}}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REVISION=${{github.ref_name}}
            VERSION=${{env.VERSION}}
